-- CRIAÇÃO DA TABELA USER_RULES
-- Execute este script no SQL Editor do Supabase

CREATE TABLE public.user_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    role TEXT NOT NULL DEFAULT 'user',
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    -- Garante que cada usuário só tenha uma regra/role
    CONSTRAINT user_rules_user_id_key UNIQUE (user_id)
);

-- Habilitar segurança (RLS)
ALTER TABLE public.user_rules ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS DE SEGURANÇA

-- 1. Leitura: Usuário pode ler sua própria regra
CREATE POLICY "Users can read own rules"
ON public.user_rules FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- 2. Inserção: Usuário pode criar sua própria regra (usado no cadastro)
CREATE POLICY "Users can insert own rules"
ON public.user_rules FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- 3. Atualização: Usuário não deve alterar sua role (somente admin), 
-- mas se necessário permitir edição própria, descomente abaixo:
-- CREATE POLICY "Users can update own rules"
-- ON public.user_rules FOR UPDATE
-- TO authenticated
-- USING (auth.uid() = user_id);
