-- SQL para Criação do Módulo de Agenda
-- Contatos e Compromissos Independentes do CRM

-- 1. Tabela de Contatos da Agenda
CREATE TABLE IF NOT EXISTS public.agenda_contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    nome TEXT NOT NULL,
    tipo TEXT DEFAULT 'Outros', -- Cliente, Parceiro, Amigo, Família, Colega, Outros
    email TEXT,
    telefone TEXT,
    empresa TEXT,
    observacoes TEXT,
    data_cadastro TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Eventos/Compromissos
CREATE TABLE IF NOT EXISTS public.agenda_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    contato_id BIGINT REFERENCES public.agenda_contatos(id) ON DELETE SET NULL,
    titulo TEXT NOT NULL,
    data_inicio TIMESTAMPTZ NOT NULL,
    data_fim TIMESTAMPTZ NOT NULL,
    descricao TEXT,
    cor TEXT DEFAULT '#3a86ff', -- Azul padrão
    status TEXT DEFAULT 'PENDENTE', -- PENDENTE, REALIZADO, CANCELADO
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Habilitar RLS
ALTER TABLE public.agenda_contatos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agenda_eventos ENABLE ROW LEVEL SECURITY;

-- 4. Criar Políticas de Segurança
CREATE POLICY "Usuários veem apenas seus contatos da agenda" 
ON public.agenda_contatos FOR ALL 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Usuários veem apenas seus eventos da agenda" 
ON public.agenda_eventos FOR ALL 
TO authenticated 
USING (auth.uid() = user_id);

-- 5. Índices para Performance
CREATE INDEX IF NOT EXISTS idx_agenda_contatos_user_id ON public.agenda_contatos(user_id);
CREATE INDEX IF NOT EXISTS idx_agenda_eventos_user_id ON public.agenda_eventos(user_id);
CREATE INDEX IF NOT EXISTS idx_agenda_eventos_data_inicio ON public.agenda_eventos(data_inicio);
CREATE INDEX IF NOT EXISTS idx_agenda_eventos_contato_id ON public.agenda_eventos(contato_id);

-- Trigger para updated_at (opcional, mas recomendado)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_agenda_contatos_updated_at BEFORE UPDATE ON public.agenda_contatos FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_agenda_eventos_updated_at BEFORE UPDATE ON public.agenda_eventos FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
