-- Adaptação do Banco de Dados para Supabase PostgreSQL (SaaS)
-- Baseado na solicitação de transformação para Gestão de Prospects

-- Configuração inicial
SET timezone = 'America/Sao_Paulo';

-- 1. Tabelas Globais (Sem user_id)
-- Segmentos
CREATE TABLE public.segmentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao TEXT NOT NULL,
    plotar BOOLEAN DEFAULT FALSE
);

-- Concorrentes (Antiga tabela sistemas)
CREATE TABLE public.concorrentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao TEXT NOT NULL,
    observacoes TEXT,
    plotar BOOLEAN DEFAULT FALSE
);

-- 2. Tabelas Por Usuário (Com user_id)

-- Vendedores
CREATE TABLE public.vendedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    nome TEXT NOT NULL,
    endereco TEXT,
    cidade TEXT,
    cep TEXT,
    uf TEXT,
    celular TEXT,
    data_cadastro TIMESTAMPTZ DEFAULT NOW()
);

-- Prospects
CREATE TABLE public.prospects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    nome TEXT NOT NULL,
    endereco TEXT,
    bairro TEXT,
    cidade TEXT,
    cep TEXT,
    uf TEXT,
    telefone TEXT,
    celular TEXT,
    contato TEXT,
    status TEXT,
    segmento_id BIGINT REFERENCES public.segmentos(id),
    concorrente_id BIGINT REFERENCES public.concorrentes(id), -- Renomeado de sistema_id
    data_cadastro TIMESTAMPTZ DEFAULT NOW(),
    ultimo_contato TIMESTAMPTZ,
    observacoes TEXT,
    vendedor TEXT, -- Mantido como TEXT conforme solicitação original (vendedor vs vendedor_id)
    email TEXT,
    classificacao TEXT
);

-- Clientes
CREATE TABLE public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    prospect_id BIGINT REFERENCES public.prospects(id),
    data_conversao TIMESTAMPTZ,
    valor_contrato NUMERIC(12,2),
    observacoes TEXT,
    tipo_contrato TEXT,
    data_inicio_contrato TIMESTAMPTZ,
    data_renovacao_contrato TIMESTAMPTZ,
    periodicidade_pagamento TEXT,
    cnpj_cpf TEXT,
    ramo_atividade TEXT,
    contato_principal TEXT,
    email_financeiro TEXT,
    fonte_captacao TEXT,
    nivel_satisfacao TEXT,
    vendedor_id BIGINT REFERENCES public.vendedores(id),
    endereco TEXT,
    cidade TEXT,
    cep TEXT,
    uf TEXT,
    telefone TEXT,
    celular TEXT,
    segmento_descricao TEXT,
    comissao NUMERIC(12,2)
);

-- Comissões
CREATE TABLE public.comissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    cliente_id BIGINT REFERENCES public.clientes(id),
    vendedor_id BIGINT REFERENCES public.vendedores(id),
    vigencia TEXT,
    valor_contrato NUMERIC(12,2),
    percentual_comissao NUMERIC(10,2),
    valor_comissao NUMERIC(12,2),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    status TEXT,
    vencimento TIMESTAMPTZ,
    observacoes TEXT
);

-- 3. Habilitar Row Level Security (RLS)

ALTER TABLE public.segmentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concorrentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comissoes ENABLE ROW LEVEL SECURITY;

-- 4. Criar Políticas de Segurança (Policies)

-- Políticas para Tabelas Globais (Leitura para todos autenticados)
CREATE POLICY "Segmentos visíveis para todos autenticados" 
ON public.segmentos FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Concorrentes visíveis para todos autenticados" 
ON public.concorrentes FOR SELECT 
TO authenticated 
USING (true);

-- Políticas para Tabelas de Usuário (Isolamento por user_id)

-- Vendedores
CREATE POLICY "Usuários veem apenas seus vendedores" 
ON public.vendedores FOR ALL 
TO authenticated 
USING (auth.uid() = user_id);

-- Prospects
CREATE POLICY "Usuários veem apenas seus prospects" 
ON public.prospects FOR ALL 
TO authenticated 
USING (auth.uid() = user_id);

-- Clientes
CREATE POLICY "Usuários veem apenas seus clientes" 
ON public.clientes FOR ALL 
TO authenticated 
USING (auth.uid() = user_id);

-- Comissões
CREATE POLICY "Usuários veem apenas suas comissões" 
ON public.comissoes FOR ALL 
TO authenticated 
USING (auth.uid() = user_id);
