-- 🚨 SCRIPT DE RESET TOTAL (V2) - EXECUTAR NO SQL EDITOR DO SUPABASE 🚨

-- 1. Limpa a estrutura antiga para evitar conflitos
DROP TABLE IF EXISTS public.user_rules;

-- 2. Cria a tabela de forma simples e direta
CREATE TABLE public.user_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE,
    role TEXT DEFAULT 'user',
    status TEXT DEFAULT 'active',
    plan_type TEXT DEFAULT 'basic',
    license_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Configura o seu usuário como ADMIN (Substitua seu email aqui)
-- IMPORTANTE: O usuário precisa já existir no Auth do Supabase
INSERT INTO public.user_rules (user_id, email, role, plan_type)
SELECT id, email, 'admin', 'premium'
FROM auth.users
WHERE email = 'juneyreis@gmail.com'
ON CONFLICT (email) DO UPDATE 
SET role = 'admin', plan_type = 'premium';

-- 4. Permissões de Segurança (RLS) Simplificadas
ALTER TABLE public.user_rules ENABLE ROW LEVEL SECURITY;

-- Todos podem ver o próprio perfil
DROP POLICY IF EXISTS "self_read" ON public.user_rules;
CREATE POLICY "self_read" ON public.user_rules 
FOR SELECT TO authenticated 
USING (auth.uid() = user_id);

-- Todos podem criar o próprio perfil
DROP POLICY IF EXISTS "self_insert" ON public.user_rules;
CREATE POLICY "self_insert" ON public.user_rules 
FOR INSERT TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- Liberar leitura geral para administradores
DROP POLICY IF EXISTS "admin_read_all" ON public.user_rules;
CREATE POLICY "admin_read_all" ON public.user_rules 
FOR SELECT TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.user_rules WHERE user_id = auth.uid() AND role = 'admin'
  )
);

-- Garantir que tabelas secundárias não fiquem órfãs
GRANT ALL ON public.user_rules TO authenticated;
GRANT ALL ON public.user_rules TO service_role;
